driver:
  rumble: true
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    b: brakeMode
    y: collectPos
  axes:
    rightTrigger: slowMode
    leftTrigger: intakeCob
  buttons:
    start: zeroPose
operator:
  rumble: false
  buttonpad:
    y: siloPos
    b: autoScore1
    a: autoScore2
  axes:
    rightTrigger: outtake
demoMode: false