driver:
  rumble: true
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    b: brakeMode
  axes:
    rightTrigger: slowMode
  buttons:
    start: zeroPose
operator:
  rumble: false
  buttonpad:
    y: siloPos
    a: collectPos
#    b: autoScore1
#    a: autoScore2
  axes:
    rightTrigger: outtake
    leftTrigger: intakeCob
demoMode: false