driver:
  rumble: false
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    b: brakeMode
  axes:
    rightTrigger: slowMode
    leftTrigger: intakeCob
  buttons:
    start: zeroPose
operator:
  rumble: false
  axes:
    rightTrigger: outtake
demoMode: false