subsystems:
  drivetrain:
    implemented: true
    talons:
      rightMain: 13
      rightFollower: 12
      leftMain: 23
      leftFollower: 3
    invertMotor:
      - rightMain
    pidConfig:
      slot0:
        kP: 1.6
        kI: 0.001
        kD: 15
        kF: 0.871875
    constants:
      ## Velocity Constraints ##
      # maxVelTicks100ms: 40275.7 # From Zodiac Pro
      encPPR: 22220.8 # From Zodiac Pro
      isSwerve: 0
      maxRotVel: 18
      trackWidth: 19.75 # inches
      wheelbaseLength: 19.75 # inches
      wheelDiameter: 4
      kTrackScrubFactor: 1.0
      maxVelOpenLoop: 3.75 # meters/s (3.6)
      maxVelPathFollowing: 3.1 # meters/s (3.6)
      maxAccel: 1.5 # meters/s^2 (2.54)
      currentLimit: 40
      isDemoMode: 0
      ## Auto Balance ##
      autoBalanceDivider: 50
      autoBalanceThreshold: 2.5 # degrees
  camera:
    implemented: false
    constants:
      useMultiTargetOdometry: 1
  elevator:
    implemented: true
    talons:
      #TODO id the motor
      heightMotor: 0
    constants:
      #TODO find these values
      elevatorZeroOffset: 0
      elevatorTicksPerMeter: 0
      allowableHeightError: 0
      humanCollectHeight: 0.7493 #height of collector
      siloDropHeight: 0.9144 #height of silo
      stowHeight: 0
infrastructure:
  canivoreBusName: rio
  ## Power Distribution ##
  pdId: 0 #This is not a placeholder/null substitute, the id is actually 0
  pdIsRev: false
  ## Pigeon ##
  pigeonId: 9
  isPigeon2: false
  ## Compressor ##
  compressorEnabled: false
  pcmId: -1
controlboard: aleph1
constants:
  # Drivetrain (Taken from Zero)
  minAllowablePoseError: 0.1
  maxAllowablePoseError: 5
  ## Logging ##
  logRobot: 1 # 0 or 1
  logDrivetrain: 1 # 0 or 1
  configStatusFrames: 0 # 0 or 1
  ## General ##
  teleopFieldCentric: 1 # 0 or 1
  kLooperDt: .025 # seconds
  resetFactoryDefaults: 0 # whether motors get reset to factory default