subsystems:
  drivetrain:
    implemented: true
    talons:
      rightMain: 13
      rightFollower: 12
      leftMain: 23
      leftFollower: 3
    invertMotor:
      - rightMain
    pidConfig:
      slot0:
        kP: 1.6
        kI: 0.001
        kD: 15
        kF: 0.871875
    constants:
      ## Velocity Constraints ##
      maxVelTicks100ms: 40275.7 # From Zodiac Pro
      encPPR: 22220.8 # Would need encoders
      openLoopRampRate: 0.8
      isSwerve: 0
      maxRotVel: 7.2
      trackWidth: 21.5 # inches (25)
      wheelbaseLength: 18.5 # inches (25)
      wheelDiameter: 6.32
      kTrackScrubFactor: 1.0
      maxVelOpenLoop: 2.5 # meters/s, Minnetrials speed limit
      maxVelPathFollowing: 2 # meters/s (3.6)
      maxAccel: 1 # meters/s^2 (2.54)
      currentLimit: 40
      isDemoMode: 0
      ## Auto Balance ##
      autoBalanceDivider: 50
      autoBalanceThreshold: 2.5 # degrees
  collector:
    implemented: true
    sparkmaxes:
      intakeMotor: 14 #change once get robot
    pidConfig:
      slot0:
        kP: 0 # Must tune if use velocity
    constants:
      intakeSpeed: -0.5
      outtakeSpeed: 0.65
  camera:
    implemented: false
    constants:
      useMultiTargetOdometry: 1
  elevator:
    implemented: true
    talons:
      spoolMotor: 6 # Use -1 as the placeholder value because 0 is a valid id
    constants:
      ascendPower: 0.75
      joltPower: 0.85
      descendPower: -0.45
      tautPower: 0
infrastructure:
  canivoreBusName: rio
  ## Power Distribution ##
  pdId: 0 #This is not a placeholder/null substitute, the id is actually 0
  pdIsRev: false
  ## Pigeon ##
  pigeonId: 9
  isPigeon2: false
  ## Compressor ##
  compressorEnabled: true
  pcmId: -1
controlboard: competition
constants:
  # Drivetrain (Taken from Zero)
  minAllowablePoseError: 0.1
  maxAllowablePoseError: 5
  ## Logging ##
  logRobot: 1 # 0 or 1
  logDrivetrain: 1 # 0 or 1
  configStatusFrames: 0 # 0 or 1
  ## General ##
  teleopFieldCentric: 1 # 0 or 1
  kLooperDt: .025 # seconds
  resetFactoryDefaults: 0 # whether motors get reset to factory default